### ISSUE TITLE
Checklist for 0.1 release

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJText.jl#5]
These are my suggestions:

- [ ] Check coverage. I'd be happy with > 80%
- [ ] Re-organize the transformer  and tests into separate files to facilitate future extension 
- [ ] Add documentation. I'd be happy with dumping the transformer docstring into the README.md for now. But if someone wants to do something more elaborate.... . My suggestion would be to keep the documentation local, ie,  not add to MLJ central docs. We can put a link there.
- [ ] Check we have complete set of [compat] entries
- [ ] Create a new `master` branch and merge a "For a 0.1 release" PR  dev -> master

@pazzo83 @storopoli Feel free to add to this.

**Comment by storopoli** [comment]
Maybe a simple "hello world" example with the documentation?

**Comment by pazzo83** [comment]
Agree on all this - what's the best way to set up coverage?  I think I saw some output in the CI where our coverage was above 80%.
In terms of reorganizing the transformer/tests - do you mean putting what we've defined into a separate file (and the corresponding tests as well)?

**Comment by ablaom** [comment]
Coverage is setup. The readme icon is not showing the coverage for reasons I do not understand, but if I click on it, it takes you to the detailed analysis (which is > 80%). As I say, that's okay with me but might be worth just scanning the analysis to see what is missing. 

> In terms of reorganizing the transformer/tests - do you mean putting what we've defined into a separate file (and the corresponding tests as well)?

Yes. Just move your code to src/tfidf_transformer.jl and your tests to test/tifid_transformer.jl and add `include`s to bring those in. Make sense?

**Comment by ablaom** [comment]
No worries. Thanks for your patience.

**Comment by storopoli** [comment]
Great!!! Happy to help you guys!
